import 'package:sew_your_stash/models/fabricType.dart';

List<FabricType> fabricTypes = [
  FabricType(type: "Woven", subTypes: [
            "Poplin",
            "Broadcloth",
            "Muslin",
            "Linen",
            "Denim",
            "Chambray",
            "Flannel",
            "Canvas",
            "Velvet",
            "Satin",
            "Chiffon",
            "Challis"]),
  FabricType(type: "Knit", subTypes: [
            "Jersey",
            "Double Knit",
            "Interlock",
            "ITY",
            "French Terry",
            "Sweater Knit",
            "Ponte",
            "Scuba",
            "Neoprene",
            "Rib Knit",
            "Athletic & Performance",
            "Swimwear",
            "Tricon Knit",
            "Fleece",
            "Sweatshirt Fleece",
            "Minky"]),
  FabricType(type: "Non-Woven", subTypes: [
            "Felt",
            "Batting",
            "Interfacing"]),
  FabricType(type: "Lace & Netting", subTypes: [
            "Tulle",
            "English Netting",
            "Mesh",
            "Alencon Lace",
            "Brussels Lace",
            "Chantilly Lace",
            "Duchess Lace",
            "Guipere Lace",
            "Schiffli Lace",
            "Lace Knitting",
            "Stretch Lace",
            "Laser Cut Lace"]),
  FabricType(type: "Other", subTypes: []),
];
